<a href="https://colab.research.google.com/github/TanyaSrivastava444/marketing-mix-model-Staffing/blob/main/Notebooks/data_cleaning_and_feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Replace 'your_file.csv' with the actual name of your uploaded CSV file
df_csv = pd.read_csv('dataset_synthetic.csv')

# Display the first 5 rows of the DataFrame
display(df_csv.head())

,week,job_board_spend,linkedin_spend,events_spend,youtube_ads_spend,google_ads_spend,client_outreach_spend,unemployment_rate,job_openings,payrolls,placements
0,2021-01-03,63476.999071,35696.019414,15365.347642,12304.755986,23322.378876,13697.912190,6.4,7204.0,142863.0,57.604871
1,2021-01-10,60618.124939,46600.859134,20231.031569,16872.251276,32966.428293,12517.459234,6.4,7204.0,142863.0,81.520929
2,2021-01-17,67684.677506,40989.321022,4843.949213,11827.014814,28924.933834,9987.365575,6.4,7204.0,142863.0,90.073056
3,2021-01-24,75335.072291,51346.952056,16436.016225,21662.842121,34619.326322,8565.925398,6.4,7204.0,142863.0,101.153439
4,2021-01-31,64495.743976,44084.567794,20782.098443,20072.024762,30014.372174,16169.189206,6.4,7204.0,142863.0,105.179272

In [4]:
#convert week to datetime
df_csv['week'] = pd.to_datetime(df_csv['week'])

In [5]:
#sorting rows by date for adstock recursion function that calculates carryover effect
df_csv = df_csv.sort_values('week')

In [6]:
#setting index - Makes week the row index. this is needed for time series modeling
df_csv = df_csv.set_index('week')

In [8]:
#missing values using forward fill assuming spend remains constant until new value appears
df_csv = df_csv.fillna(method="ffill")

/tmp/ipykernel_1474/1898542296.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_csv = df_csv.fillna(method="ffill")

In [9]:
# feautures list - apply transformations programmatically
channels = [
"job_board_spend",
"linkedin_spend",
"events_spend",
"youtube_ads_spend",
"google_ads_spend",
"client_outreach_spend"
]

In [11]:
macro_vars = [
"unemployment_rate",
"job_openings",
"payrolls"
]

In [10]:
## Scaling - transforms variables between 0-1  no scaling will throw gradient descent off
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

df_csv[channels] = scaler.fit_transform(df_csv[channels])
df_csv[macro_vars] = scaler.fit_transform(df_csv[macro_vars])

In [13]:
df_csv.head()

,job_board_spend,linkedin_spend,events_spend,youtube_ads_spend,google_ads_spend,client_outreach_spend,unemployment_rate,job_openings,payrolls,placements
week,,,,,,,,,,
2021-01-03,-0.524041,-1.891748,-1.433125,-1.400482,-1.917682,0.731560,2.072289,-2.736924,-1.917194,57.604871
2021-01-10,-0.751895,-0.725998,-0.598354,-0.168823,-0.335504,0.291253,2.072289,-2.736924,-1.917194,81.520929
2021-01-17,-0.188687,-1.325883,-3.238207,-1.529308,-0.998541,-0.652469,2.072289,-2.736924,-1.917194,90.073056
2021-01-24,0.421053,-0.218631,-1.249438,1.122995,-0.064334,-1.182664,2.072289,-2.736924,-1.917194,101.153439
2021-01-31,-0.442846,-0.994995,-0.503811,0.694020,-0.819811,1.653343,2.072289,-2.736924,-1.917194,105.179272